#!/bin/sh

set -e

tmux list-sessions | grep -q offlineimap && exit 1
tmux list-sessions | grep -q mailfilter && exit 1

mailfilter $HOME/.mail/metanohi
mailfilter-muttrc-generate $HOME/.mail/metanohi > $HOME/.mutt/mailboxes
